import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../api/axios';
import { Tag, Plus, ArrowRight } from 'lucide-react';

export default function SellerOffersPage() {
  const [activeTab, setActiveTab] = useState('all');
  const [offers, setOffers] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchOffers();
  }, []);

  const fetchOffers = async () => {
    try {
      const res = await api.get('/seller/offers');
      setOffers(res.data.offers || []);
    } catch (err) {
      console.error('Failed to fetch seller offers:', err);
    } finally {
      setLoading(false);
    }
  };

  const filteredOffers = offers.filter(o => {
    if (activeTab === 'accepted') return o.status === 'ACCEPTED' || o.status === 'VALID';
    if (activeTab === 'pending') return o.status === 'PENDING' || o.status === 'SUBMITTED';
    return true;
  });

  return (
    <div className="max-w-[1280px] mx-auto px-4 sm:px-8 py-8 space-y-6 font-sans text-[#20284F]">
      
      {/* Header */}
      <div>
        <h1 className="text-2xl font-extrabold text-[#20284F] tracking-tight">My Offers</h1>
        <p className="text-xs text-[#20284F]/70 font-medium mt-0.5">
          Track submitted AI policy offers and buyer negotiation statuses
        </p>
      </div>

      {/* Tabs */}
      <div className="flex items-center space-x-2 border-b border-[#EAE3D9] pb-3 text-xs font-semibold">
        <button
          onClick={() => setActiveTab('all')}
          className={`px-3.5 py-1.5 rounded-full transition-all ${
            activeTab === 'all'
              ? 'bg-gradient-to-r from-[#20284F] via-[#352F6E] to-[#7668D8] text-white shadow-md'
              : 'text-[#20284F]/70 hover:bg-[#FAF6F0]'
          }`}
        >
          All Submitted Offers ({offers.length})
        </button>
        <button
          onClick={() => setActiveTab('accepted')}
          className={`px-3.5 py-1.5 rounded-full transition-all ${
            activeTab === 'accepted'
              ? 'bg-gradient-to-r from-[#20284F] via-[#352F6E] to-[#7668D8] text-white shadow-md'
              : 'text-[#20284F]/70 hover:bg-[#FAF6F0]'
          }`}
        >
          Accepted Deals
        </button>
        <button
          onClick={() => setActiveTab('pending')}
          className={`px-3.5 py-1.5 rounded-full transition-all ${
            activeTab === 'pending'
              ? 'bg-gradient-to-r from-[#20284F] via-[#352F6E] to-[#7668D8] text-white shadow-md'
              : 'text-[#20284F]/70 hover:bg-[#FAF6F0]'
          }`}
        >
          Pending Review
        </button>
      </div>

      {/* Offers Cards List or Clean Zero State */}
      {filteredOffers.length === 0 ? (
        <div className="bg-white border border-[#EAE3D9] rounded-2xl p-12 text-center space-y-4 shadow-sm">
          <div className="w-14 h-14 rounded-2xl bg-[#FAF6F0] text-[#7668D8] border border-[#EAE3D9] flex items-center justify-center mx-auto">
            <Tag className="w-7 h-7" />
          </div>
          <div className="space-y-1">
            <h3 className="font-bold text-[#20284F] text-lg">No Active Offers Yet</h3>
            <p className="text-xs text-[#20284F]/70 max-w-md mx-auto font-medium">
              Offers generated by your AI policy engine for buyer requests will be tracked here. Ensure your products are listed in your catalog to generate automated offers.
            </p>
          </div>
          <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
            <Link
              to="/seller/catalog"
              className="px-5 py-2.5 bg-gradient-to-r from-[#20284F] via-[#352F6E] to-[#7668D8] hover:opacity-95 text-white font-bold text-xs rounded-xl shadow-md transition-all flex items-center space-x-1.5"
            >
              <Plus className="w-4 h-4" />
              <span>Add Products to Catalog</span>
            </Link>
            <Link
              to="/seller/requests"
              className="px-5 py-2.5 bg-[#FAF6F0] border border-[#EAE3D9] text-[#20284F] hover:bg-[#EAE3D9]/50 font-bold text-xs rounded-xl shadow-xs transition-all flex items-center space-x-1.5"
            >
              <span>View Buyer Requests</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredOffers.map(o => (
            <div key={o.id || o.offer_id} className="bg-white border border-[#EAE3D9] rounded-2xl p-6 shadow-sm hover:shadow-md transition-all space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#EAE3D9]/60 pb-3">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 rounded-xl bg-[#FAF6F0] text-[#7668D8] border border-[#EAE3D9] flex items-center justify-center shrink-0">
                    <Tag className="w-5 h-5" />
                  </div>
                  <div>
                    <div className="flex items-center space-x-2">
                      <span className="text-xs font-mono font-bold text-[#20284F]/50">{o.id}</span>
                      <h3 className="font-bold text-[#20284F] text-sm">{o.buyer_company || o.buyer_name}</h3>
                    </div>
                    <div className="text-[11px] text-[#20284F]/60 font-medium">Submitted on {new Date(o.created_at || Date.now()).toLocaleDateString()}</div>
                  </div>
                </div>

                <span className={`text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-wider ${
                  o.status === 'ACCEPTED' || o.status === 'VALID'
                    ? 'bg-emerald-500/10 text-emerald-700 border border-emerald-500/20'
                    : 'bg-amber-500/10 text-amber-700 border border-amber-500/20'
                }`}>
                  {o.status}
                </span>
              </div>

              <p className="text-xs text-[#20284F] italic bg-[#FAF6F0] p-3 rounded-xl border border-[#EAE3D9]/60">
                "{o.raw_prompt}"
              </p>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-3 bg-[#FAF6F0] rounded-xl border border-[#EAE3D9]/60 text-xs">
                <div>
                  <span className="text-[#20284F]/60 font-medium block">Original Price</span>
                  <strong className="text-[#20284F] font-mono">₹{Number(o.original_amount || 0).toLocaleString('en-IN')}</strong>
                </div>

                <div>
                  <span className="text-[#20284F]/60 font-medium block">Negotiated Offer</span>
                  <strong className="text-[#7668D8] font-mono text-sm">₹{Number(o.negotiated_amount || 0).toLocaleString('en-IN')}</strong>
                </div>

                <div>
                  <span className="text-[#20284F]/60 font-medium block">Discount Given</span>
                  <strong className="text-emerald-600 font-mono">₹{Number(o.savings || 0).toLocaleString('en-IN')}</strong>
                </div>

                <div>
                  <span className="text-[#20284F]/60 font-medium block">Status</span>
                  <strong className="text-[#20284F] font-mono">{o.is_best_deal ? '★ Best Deal' : 'Submitted'}</strong>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

    </div>
  );
}
